### ISSUE TITLE
Would it be okay to download your project, convert it to Gerber files, and then manufacture the PCB?

### ISSUE THREAD

**Issue by drawingangnam** [btb/CPIIMiniMem#1]
Hello. I pay my respects to your wonderful project. 
It's a grateful gift for someone like me who loves retro devices. 
I think my CP2 will become even more amazing. 
Would it be okay if I download this project and manufacture the PCB?

**Comment by btb** [comment]
You certainly may do that, yes. This is still just a first revision, though it does work. Note that since it only has one bank of simms, it currently only supports adding 512K of RAM.
